In [47]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense

In [59]:
def prepare_data(timeseries_data,n_features):
    X, y = [], []
    for i in range(len(timeseries_data)):
        end_i = i + n_features
        if end_i > len(timeseries_data)-1:
            break
        seq_x, seq_y = timeseries_data[i:end_i],timeseries_data[end_i]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)
        

In [60]:
timeseries_data = [110, 125, 133, 146, 158, 172, 187, 196, 210]
n_steps = 3
X,y = prepare_data(timeseries_data,n_steps)
print(X,y)

[[110 125 133]
 [125 133 146]
 [133 146 158]
 [146 158 172]
 [158 172 187]
 [172 187 196]] [146 158 172 187 196 210]


In [61]:
X.shape

(6, 3)

In [62]:
# Reshape from [sample, timesteps] into [sample, timestep, features]
n_feature = 1
X = X.reshape(X.shape[0], X.shape[1], n_feature)

In [63]:
X.shape

(6, 3, 1)

# Building LSTM model

In [64]:
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps,n_feature), return_sequences=True))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit(X,y,epochs=300,verbose=0)

In [66]:
x_input = np.array([187, 196, 210])
temp_input = list(x_input)
lst_output = []
i = 0
while i<10:
    if (len(temp_input) > 3):
        x_input = np.array(temp_input[1:])
        print("{} day input is {}".format(i, x_input))
        x_input = x_input.reshape((1, n_steps, n_feature))
        yhat = model.predict(x_input,verbose=0)
        print("{} day output is {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input = temp_input[1:]
        lst_output.append(yhat[0][0])
        i = i+1
    else:
        x_input = x_input.reshape(1, n_steps, n_feature)
        yhat = model.predict(x_input,verbose=0)
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i = i+1
        
        
        
print(lst_output)

1 day input is [196.         210.         222.85118103]
1 day output is [[234.41183]]
2 day input is [210.         222.85118103 234.41183472]
2 day output is [[248.29294]]
3 day input is [222.85118 234.41183 248.29294]
3 day output is [[261.92828]]
4 day input is [234.41183 248.29294 261.92828]
4 day output is [[275.42593]]
5 day input is [248.29294 261.92828 275.42593]
5 day output is [[290.228]]
6 day input is [261.92828 275.42593 290.228  ]
6 day output is [[305.24347]]
7 day input is [275.42593 290.228   305.24347]
7 day output is [[320.569]]
8 day input is [290.228   305.24347 320.569  ]
8 day output is [[336.80893]]
9 day input is [305.24347 320.569   336.80893]
9 day output is [[353.50757]]
[222.85118, 234.41183, 248.29294, 261.92828, 275.42593, 290.228, 305.24347, 320.569, 336.80893, 353.50757]


# Visualizing the output

In [67]:
import matplotlib.pyplot as plt

In [68]:
day_new = np.arange(1,10)
day_pred = np.arange(10,20)


In [ ]:
plt.po